steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_ENV_IMG_NAME}:${_ENV}",
        ".",
      ]
    dir: "back"
    # push the container image

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_ENV_IMG_NAME}:${_ENV}",
      ]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_ENV_IMG_NAME}:${_ENV}",
        "--region",
        "europe-central2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080"
      ]
options:
  logging: CLOUD_LOGGING_ONLY